apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kurrentdb-operator
  namespace: flux-system
spec:
  releaseName: kurrentdb-operator
  interval: 30m
  chart:
    spec:
      chart: kurrentdb-operator
      version: "1.3.x"
      sourceRef:
        kind: HelmRepository
        name: kurrentdb
        namespace: flux-system
      interval: 12h
  targetNamespace: kurrentdb-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Global configuration
    commonLabels:
      app.kubernetes.io/managed-by: flux
    # Operator configuration
    image:
      repository: ghcr.io/kurrent-io/kurrentdb-operator
      tag: "v1.3.0"
      pullPolicy: IfNotPresent
    
    # Resource limits for the operator
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    
    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
      seccompProfile:
        type: RuntimeDefault
    
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    
    # Node selector and tolerations
    nodeSelector: {}
    tolerations: []
    affinity: {}
    
    # Operator replicas
    replicaCount: 1
    
    # Service account
    serviceAccount:
      create: true
      annotations: {}
      name: ""
    
    # RBAC
    rbac:
      create: true
    
    # Monitoring
    metrics:
      enabled: true
      port: 8080
      path: /metrics
      serviceMonitor:
        enabled: true
        namespace: monitoring
        interval: 30s
        scrapeTimeout: 10s
        labels:
          app.kubernetes.io/name: kurrentdb-operator
    
    # Webhook configuration
    webhook:
      enabled: true
      port: 9443
      certManager:
        enabled: true
      
    # Leader election
    leaderElection:
      enabled: true
      leaseDuration: 15s
      renewDeadline: 10s
      retryPeriod: 2s
    
    # Log level and format
    logLevel: info
    logFormat: json
    
    # Health checks
    healthChecks:
      enabled: true
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8081
        initialDelaySeconds: 15
        periodSeconds: 20
      readinessProbe:
        httpGet:
          path: /readyz
          port: 8081
        initialDelaySeconds: 5
        periodSeconds: 10
    
    # CRD management
    crds:
      create: true
      annotations: {}
    
    # Pod disruption budget
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    
    # Network policies
    networkPolicy:
      enabled: false
    
    # Priority class
    priorityClassName: ""
    
    # Additional labels and annotations
    commonLabels:
      app.kubernetes.io/name: kurrentdb-operator
      app.kubernetes.io/component: operator
    
    commonAnnotations: {}
    
    # Environment-specific configuration
    env:
      - name: WATCH_NAMESPACE
        value: ""  # Watch all namespaces
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: OPERATOR_NAME
        value: "kurrentdb-operator"
