apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  labels:
    region: westeurope
    environment: stage
spec:
  chart:
    spec:
      version: "4.8.x"
  values:
    controller:
      replicaCount: 2
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
      nodeSelector:
        topology.kubernetes.io/region: westeurope
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-resource-group: "rg-westeurope-stage"
