apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cert-manager/
  - ../../../base/external-secrets/
  - ../../../base/ingress-nginx/
  - ../../../base/kube-prometheus-stack/
  - ../../../base/kurrentdb-monitoring/

# Add environment and region labels
commonLabels:
  environment: prod
  region: eastasia
  topology.kubernetes.io/region: eastasia

# Strategic merge patches for regional configuration
patchesStrategicMerge:
  - cert-manager-patch.yaml
  - external-secrets-patch.yaml
  - ingress-nginx-patch.yaml
  - kube-prometheus-stack-patch.yaml
  - kurrentdb-monitoring-patch.yaml
