apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  labels:
    region: eastasia
    environment: dev
spec:
  chart:
    spec:
      version: "v1.13.x"
  values:
    replicaCount: 1
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
    nodeSelector:
      topology.kubernetes.io/region: eastasia
