# Staging environment patches for KurrentDB monitoring
# Moderate thresholds for pre-production testing
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kurrentdb-alerts
  namespace: monitoring
spec:
  groups:
    - name: kurrentdb.critical
      rules:
        # Override instance down alert for stage
        - alert: KurrentDBInstanceDown
          expr: up{job=~".*kurrentdb.*"} == 0
          for: 1m # Moderate response time for stage
          labels:
            severity: warning # Less critical than prod
            component: kurrentdb
            environment: stage
            region: eastasia
          annotations:
            summary: "KurrentDB instance {{ $labels.instance }} is down (STAGE)"
            description: "KurrentDB instance {{ $labels.instance }} in staging environment has been down for more than 1 minute."
            runbook_url: "https://docs.kurrent.io/server/v25.0/diagnostics/"

        # Override CPU alert for stage (moderate threshold)
        - alert: KurrentDBHighCPU
          expr: rate(kurrentdb_process_cpu_total[5m]) * 100 > 75 # Moderate threshold for stage
          for: 5m
          labels:
            severity: warning
            component: kurrentdb
            environment: stage
            region: eastasia
          annotations:
            summary: "KurrentDB high CPU usage on {{ $labels.instance }} (STAGE)"
            description: "KurrentDB instance {{ $labels.instance }} in staging environment CPU usage is {{ $value }}% for more than 5 minutes."

        # Override memory alert for stage (moderate threshold)
        - alert: KurrentDBHighMemory
          expr: kurrentdb_process_memory_working_set_bytes / kurrentdb_process_memory_limit_bytes * 100 > 85 # Moderate threshold for stage
          for: 5m
          labels:
            severity: warning
            component: kurrentdb
            environment: stage
            region: eastasia
          annotations:
            summary: "KurrentDB high memory usage on {{ $labels.instance }} (STAGE)"
            description: "KurrentDB instance {{ $labels.instance }} in staging environment memory usage is {{ $value }}% for more than 5 minutes."

        # Override disk space alert for stage (moderate threshold)
        - alert: KurrentDBDiskSpaceLow
          expr: kurrentdb_drive_available_bytes / kurrentdb_drive_total_bytes * 100 < 10 # Same as base for stage
          for: 3m
          labels:
            severity: warning
            component: kurrentdb
            environment: stage
            region: eastasia
          annotations:
            summary: "KurrentDB low disk space on {{ $labels.instance }} (STAGE)"
            description: "KurrentDB instance {{ $labels.instance }} in staging environment has less than {{ $value }}% disk space available."

        # Staging-specific performance monitoring
        - alert: KurrentDBHighWriteLatencyStage
          expr: rate(kurrentdb_writer_flush_duration_seconds_sum[5m]) / rate(kurrentdb_writer_flush_duration_seconds_count[5m]) > 0.4 # Moderate for stage
          for: 5m
          labels:
            severity: warning
            component: kurrentdb
            environment: stage
            region: eastasia
          annotations:
            summary: "KurrentDB high write latency on {{ $labels.instance }} (STAGE)"
            description: "KurrentDB instance {{ $labels.instance }} in staging has high write latency of {{ $value }}s for more than 5 minutes."

        # Connection monitoring for stage
        - alert: KurrentDBHighConnectionCountStage
          expr: kurrentdb_tcp_connections_current > 80 # Lower threshold for stage
          for: 10m
          labels:
            severity: warning
            component: kurrentdb
            environment: stage
            region: eastasia
          annotations:
            summary: "KurrentDB high connection count on {{ $labels.instance }} (STAGE)"
            description: "KurrentDB instance {{ $labels.instance }} in staging has {{ $value }} concurrent connections for more than 10 minutes."
