apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
  labels:
    region: westeurope
    environment: dev
spec:
  chart:
    spec:
      version: "v1.13.x"
  values:
    nodeSelector:
      topology.kubernetes.io/region: westeurope
