apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
  labels:
    region: westeurope
    environment: dev
spec:
  chart:
    spec:
      version: "55.x"
  values:
    commonLabels:
      environment: dev
      region: westeurope
      topology.kubernetes.io/region: westeurope
    # Regional hostnames for Western Europe Dev
    grafana:
      ingress:
        hosts:
          - "grafana-westeurope-dev.example.com"
        tls:
          - hosts:
              - "grafana-westeurope-dev.example.com"
      nodeSelector:
        topology.kubernetes.io/region: westeurope
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: "kurrentdb"
              orgId: 1
              folder: "KurrentDB"
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/kurrentdb
      dashboards:
        kurrentdb:
          # Community EventStore dashboard (works with KurrentDB)
          eventstore-community:
            gnetId: 7673
            revision: 5
            datasource: Prometheus
          # KurrentDB panels
          kurrentdb-panels:
            gnetId: 22823
            revision: 1
            datasource: Prometheus

    prometheus:
      ingress:
        hosts:
          - "prometheus-westeurope-dev.example.com"
        tls:
          - hosts:
              - "prometheus-westeurope-dev.example.com"
      prometheusSpec:
        nodeSelector:
          topology.kubernetes.io/region: westeurope
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        retention: "7d"
        retentionSize: "5GB"

    alertmanager:
      ingress:
        hosts:
          - "alertmanager-westeurope-dev.example.com"
        tls:
          - hosts:
              - "alertmanager-westeurope-dev.example.com"
      alertmanagerSpec:
        nodeSelector:
          topology.kubernetes.io/region: westeurope
